apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "d2.fullname" . }}
  labels:
    {{- include "d2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "d2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "d2.selectorLabels" . | nindent 8 }}
      annotations:
        # Make sure that the pods are recreated automatically
        timestamp: {{ now | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        tty: true
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        volumeMounts:
        - name: d2-local
          mountPath: {{ .Values.paths.install }}/local
        - name: d2-config
          mountPath: {{ .Values.paths.config }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
      - name: init-local
        image: busybox:1.34
        command: ['sh', '-c', "for cfg in adminWhitelist.json config.json netApiKeys.json platformTokens.json; do ln -sf {{ .Values.paths.config }}/$cfg {{ .Values.paths.install }}/local/$cfg; done"]
        volumeMounts:
        - name: d2-local
          mountPath: {{ .Values.paths.install }}/local
      volumes:
      - name: d2-local
        persistentVolumeClaim:
          claimName: {{ include "d2.fullname" . }}-local-claim
      - name: d2-config
        configMap:
          name: {{ include "d2.fullname" . }}-config
      restartPolicy: {{ .Values.restartPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
