apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "d2.fullname" . }}-local-claim
  labels:
    {{- include "d2.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageClaim.size | quote }}
