image: "swift:5.8"

stages:
  - build

build:
  stage: build
  script:
    - Scripts/install-build-dependencies-apt
    - swift test -c release
  artifacts:
    paths:
      - ./.build/release/D2
    expire_in: 1 week
