image: "swift:5.7"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - Scripts/install-build-dependencies-apt
    - swift test -c release
  artifacts:
    paths:
      - ./.build/release/D2
    expire_in: 1 week

deploy:
  image:
    name: docker/compose:1.24.1
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - docker-compose build
    - docker-compose up -d
