#!/bin/sh

echo "Current contents of D2's local volume:"
ls /d2/local

echo "Config:"
echo $D2_CONFIG

echo "Now copying config data from environment variables to files..."
echo $D2_ADMIN_WHITELIST | base64 -d > /d2/local/adminWhitelist.json
echo $D2_CONFIG | base64 -d > /d2/local/config.json
echo $D2_PLATFORM_TOKENS | base64 -d > /d2/local/platformTokens.json
echo $D2_NET_API_KEYS | base64 -d > /d2/local/netApiKeys.json
