#!/bin/bash

# Installs all apt dependencies that are needed to build D2.

set -e
cd "$(dirname $0)/.."

dependencies=(
  libcairo2-dev
  libsqlite3-dev
  libleptonica-dev
  libtesseract-dev
  libgraphviz-dev
  # TODO: poppler-utils and libssl1.1 needed?
)

echo "==> Installing ${dependencies[@]}"
apt-get update
apt-get install -y "${dependencies[@]}"
