#!/bin/bash

# Installs all apt dependencies that are needed to build D2.

set -e
cd "$(dirname $0)/.."

dependencies=(
  libcairo2-dev
  libsqlite3-dev
  libleptonica-dev
  libtesseract-dev
  libgraphviz-dev
  libstdc++-12-dev
  # TODO: poppler-utils and libssl1.1 needed?
)

echo "==> Installing add-apt-repository"
apt-get update
apt-get install -y software-properties-common

echo "==> Enabling all repositories"
for repo in main universe multiverse; do
  add-apt-repository $repo
done

echo "==> Installing ${dependencies[@]}"
apt-get update
apt-get install -y "${dependencies[@]}"
