#!/bin/bash

# Installs all Haskell packages that are needed to run D2's Haskell-related commands

set -e

if [ $# -lt 1 ]; then
  echo "Usage: $0 <stack or cabal> [additional flags...]"
  exit 1
fi

tool="$1"
shift

"$tool" install "$@" happy show mueval pointfree pointful
