#!/bin/bash

# Installs all npm packages that are needed to run D2's Node.js-based commands.

set -e
cd "$(dirname $0)/.."

cd Node

for dir in */; do
  (cd "$dir" && npm install --fetch-timeout=60000)
done
