#!/bin/bash

# Restores FFI includes from the command-line tools.

set -e
cd "$(dirname $0)/.."

find "/Library/Developer/CommandLineTools/SDKs" \
  -name "MacOSX*.sdk" \
  -type d \
  -depth 1 \
  -exec bash -c 'ffidir={}/usr/include/ffi && [ -d "$ffidir.backup" ] && echo "Moving $ffidir.backup to $ffidir..." && sudo mv "$ffidir"{.backup,}' \;
