#!/bin/bash

# Unfortunately, Docker uses a different name for some CPU architectures than some
# Linux tools (arm64 vs aarch64, amd64 vs x86_64, ...), therefore we use this script
# to perform this mapping once and for all.

set -e

if [ $# -lt 1 ]; then
  echo "Usage: $0 [arch name]"
  exit 1
fi

case "$1" in
  amd64) echo "x86_64";;
  arm64) echo "aarch64";;
  *)     echo "$1";;
esac
