name: Build

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-14']
        swift: ['5.10']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install native dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo Scripts/install-build-dependencies-apt
    - name: Install native dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        # Work around an upstream issue with the runner image:
        # https://github.com/actions/runner-images/issues/8500
        brew upgrade || brew link --overwrite python@3.11

        Scripts/install-dependencies-brew
    - name: Install Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build
    - name: Test
      run: swift test
