name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          swift: '5.7'
        - os: macos-12
          swift: '5.7'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      # Workaround, see script for details
    - name: Remove duplicate FFI includes (macOS)
      if: runner.os == 'macOS'
      run: Scripts/remove-commandlinetools-ffi-includes
    - name: Install native dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo Scripts/install-build-dependencies-apt
    - name: Install native dependencies (macOS)
      if: runner.os == 'macOS'
      run: Scripts/install-dependencies-brew
    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build
    - name: Test
      run: swift test
