name: Deploy

on:
  workflow_run:
    workflows:
    - Docker
    types:
    - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3
    - name: Configure Kubernetes context
      run: |
        mkdir ~/.kube
        echo "${{ secrets.PROD_KUBECTL }}" | base64 --decode > ~/.kube/config
    - name: Set up values
      run: |
        mkdir local
        version="$(Scripts/get-version)"
        cat << EOF > local/values.yaml
        d2:
          adminWhitelist:
            users:
            - value: '${{ secrets.PROD_ADMIN_USER }}'
              clientName: Discord
          config:
            commandPrefix: '%'
            hostInfo:
              instanceName: 'prod/k8s/gh-actions/$version'
          platformTokens:
            discord: '${{ secrets.PROD_DISCORD_TOKEN }}'
          netApiKeys:
            mapQuest: '${{ secrets.MAPQUEST_TOKEN }}'
            wolframAlpha: '${{ secrets.WOLFRAM_ALPHA_TOKEN }}'
            openweathermap: '${{ secrets.OPENWEATHERMAP_TOKEN }}'
            tier: '${{ secrets.TIER_TOKEN }}'
            windy:
              webcams: '${{ secrets.WINDY_WEBCAMS_TOKEN }}'
            genius: '${{ secrets.GENIUS_TOKEN }}'
            adventOfCode:
              '2022': '${{ secrets.ADVENT_OF_CODE_2022_TOKEN }}'
            giphy: '${{ secrets.GIPHY_TOKEN }}'
        EOF
    - name: Deploy Helm chart
      run: helm upgrade --install -f local/values.yaml d2 Helm/d2
