name: Deploy

on:
  workflow_run:
    workflows:
    - Docker
    types:
    - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: (github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch') && github.repository == 'fwcd/d2' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Trigger deployment
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DEPLOY_GITHUB_PAT }}
        repository: pesca-dev/d2-deploy
        event-type: d2-deploy-trigger
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
